-- Test schema initialization for Oracle DB
-- This script creates test tables and populates them with sample data

-- Create TESTUSER schema tables
CREATE TABLE TESTUSER.DEPARTMENT (
    DEPT_ID NUMBER(10) PRIMARY KEY,
    DEPT_NAME VARCHAR2(100) NOT NULL,
    LOCATION VARCHAR2(100),
    BUDGET NUMBER(15,2)
);

CREATE TABLE TESTUSER.EMPLOYEE (
    EMP_ID NUMBER(10) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(20),
    HIRE_DATE DATE NOT NULL,
    SALARY NUMBER(10,2),
    BIO CLOB,
    DEPT_ID NUMBER(10),
    MANAGER_ID NUMBER(10),
    CONSTRAINT fk_emp_dept FOREIGN KEY (DEPT_ID) REFERENCES TESTUSER.DEPARTMENT(DEPT_ID)
);

CREATE TABLE TESTUSER.JOB_HISTORY (
    EMPLOYEE_ID NUMBER(10),
    START_DATE DATE,
    END_DATE DATE,
    JOB_TITLE VARCHAR2(100) NOT NULL,
    DEPARTMENT_ID NUMBER(10),
    CONSTRAINT pk_job_history PRIMARY KEY (EMPLOYEE_ID, START_DATE),
    CONSTRAINT fk_jobhist_emp FOREIGN KEY (EMPLOYEE_ID) REFERENCES TESTUSER.EMPLOYEE(EMP_ID),
    CONSTRAINT fk_jobhist_dept FOREIGN KEY (DEPARTMENT_ID) REFERENCES TESTUSER.DEPARTMENT(DEPT_ID)
);

CREATE TABLE TESTUSER.COMPARE_SOURCE (
    ID NUMBER(10) PRIMARY KEY,
    STATUS VARCHAR2(30),
    UPDATED_BY VARCHAR2(50),
    DESCRIPTION CLOB
);

CREATE TABLE TESTUSER.COMPARE_TARGET (
    ID NUMBER(10) PRIMARY KEY,
    STATUS VARCHAR2(30),
    UPDATED_BY VARCHAR2(50),
    DESCRIPTION CLOB
);

-- Insert test data for DEPARTMENT
INSERT INTO TESTUSER.DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION, BUDGET)
VALUES (1, 'Engineering', 'San Francisco', 1000000.00);

INSERT INTO TESTUSER.DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION, BUDGET)
VALUES (2, 'Sales', 'New York', 750000.00);

INSERT INTO TESTUSER.DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION, BUDGET)
VALUES (3, 'HR', 'Chicago', 500000.00);

-- Insert test data for EMPLOYEE
INSERT INTO TESTUSER.EMPLOYEE (EMP_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, HIRE_DATE, SALARY, DEPT_ID, MANAGER_ID)
VALUES (1, 'John', 'Doe', 'john.doe@example.com', '555-0101', TO_DATE('2020-01-15', 'YYYY-MM-DD'), 85000.00, 1, NULL);

INSERT INTO TESTUSER.EMPLOYEE (EMP_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, HIRE_DATE, SALARY, DEPT_ID, MANAGER_ID)
VALUES (2, 'Jane', 'Smith', 'jane.smith@example.com', '555-0102', TO_DATE('2020-03-20', 'YYYY-MM-DD'), 75000.00, 1, 1);

INSERT INTO TESTUSER.EMPLOYEE (EMP_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, HIRE_DATE, SALARY, DEPT_ID, MANAGER_ID)
VALUES (3, 'Bob', 'Johnson', 'bob.johnson@example.com', '555-0103', TO_DATE('2021-06-10', 'YYYY-MM-DD'), 65000.00, 2, 1);

INSERT INTO TESTUSER.EMPLOYEE (EMP_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, HIRE_DATE, SALARY, DEPT_ID, MANAGER_ID)
VALUES (4, 'Alice', 'Williams', 'alice.williams@example.com', '555-0104', TO_DATE('2021-09-01', 'YYYY-MM-DD'), 70000.00, 3, 1);

INSERT INTO TESTUSER.EMPLOYEE (EMP_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, HIRE_DATE, SALARY, DEPT_ID, MANAGER_ID)
VALUES (5, 'Charlie', 'Brown', 'charlie.brown@example.com', '555-0105', TO_DATE('2022-01-15', 'YYYY-MM-DD'), 60000.00, 2, 3);

-- Insert test data for JOB_HISTORY
INSERT INTO TESTUSER.JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_TITLE, DEPARTMENT_ID)
VALUES (2, TO_DATE('2020-03-20', 'YYYY-MM-DD'), TO_DATE('2021-03-20', 'YYYY-MM-DD'), 'Junior Developer', 1);

INSERT INTO TESTUSER.JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_TITLE, DEPARTMENT_ID)
VALUES (2, TO_DATE('2021-03-21', 'YYYY-MM-DD'), NULL, 'Senior Developer', 1);

INSERT INTO TESTUSER.JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_TITLE, DEPARTMENT_ID)
VALUES (3, TO_DATE('2021-06-10', 'YYYY-MM-DD'), NULL, 'Sales Representative', 2);

-- Insert test data for compare workflow
INSERT INTO TESTUSER.COMPARE_SOURCE (ID, STATUS, UPDATED_BY, DESCRIPTION)
VALUES (
    1,
    'APPROVED',
    'SOURCE_USER',
    'source long text payload ' || RPAD('x', 150, 'x')
);

INSERT INTO TESTUSER.COMPARE_TARGET (ID, STATUS, UPDATED_BY, DESCRIPTION)
VALUES (
    1,
    'PENDING',
    'TARGET_USER',
    'target long text payload ' || RPAD('y', 150, 'y')
);

INSERT INTO TESTUSER.COMPARE_SOURCE (ID, STATUS, UPDATED_BY, DESCRIPTION)
VALUES (2, 'MATCHED', 'SOURCE_USER', 'same text');

INSERT INTO TESTUSER.COMPARE_TARGET (ID, STATUS, UPDATED_BY, DESCRIPTION)
VALUES (2, 'MATCHED', 'TARGET_USER', 'same text');

INSERT INTO TESTUSER.COMPARE_SOURCE (ID, STATUS, UPDATED_BY, DESCRIPTION)
VALUES (3, 'NEW', 'SOURCE_USER', 'source-only row');

-- Comprehensive type tables for review approve integration tests
CREATE TABLE TESTUSER.ALLTYPE_SOURCE (
    ID          NUMBER(10)   PRIMARY KEY,
    INT_VAL     NUMBER(10),
    DEC_VAL     NUMBER(15,6),
    STR_VAL     VARCHAR2(200),
    DATE_VAL    DATE,
    TS_VAL      TIMESTAMP(6),
    CLOB_VAL    CLOB,
    NULL_VAL    VARCHAR2(100)
);

CREATE TABLE TESTUSER.ALLTYPE_TARGET (
    ID          NUMBER(10)   PRIMARY KEY,
    INT_VAL     NUMBER(10),
    DEC_VAL     NUMBER(15,6),
    STR_VAL     VARCHAR2(200),
    DATE_VAL    DATE,
    TS_VAL      TIMESTAMP(6),
    CLOB_VAL    CLOB,
    NULL_VAL    VARCHAR2(100)
);

-- Row 10: UPDATE — source has rich values, target has stale values
INSERT INTO TESTUSER.ALLTYPE_SOURCE (ID, INT_VAL, DEC_VAL, STR_VAL, DATE_VAL, TS_VAL, CLOB_VAL, NULL_VAL)
VALUES (10, 42, 123.456789, 'source text',
        TO_DATE('2023-06-15', 'YYYY-MM-DD'),
        TIMESTAMP '2023-06-15 10:30:00.123456',
        'short clob source', 'not null');

INSERT INTO TESTUSER.ALLTYPE_TARGET (ID, INT_VAL, DEC_VAL, STR_VAL, DATE_VAL, TS_VAL, CLOB_VAL, NULL_VAL)
VALUES (10, 1, 1.000000, 'old text',
        TO_DATE('2020-01-01', 'YYYY-MM-DD'),
        TIMESTAMP '2020-01-01 00:00:00.000000',
        'old clob', 'old null value');

-- Row 11: UPDATE NULL — source NULL_VAL is NULL, target has a value
INSERT INTO TESTUSER.ALLTYPE_SOURCE (ID, STR_VAL, NULL_VAL)
VALUES (11, 'source str', NULL);

INSERT INTO TESTUSER.ALLTYPE_TARGET (ID, STR_VAL, NULL_VAL)
VALUES (11, 'old str', 'has value');

-- Row 12: UPDATE large CLOB — CLOB_VAL will be replaced with >4000 chars in test setup
INSERT INTO TESTUSER.ALLTYPE_SOURCE (ID, CLOB_VAL)
VALUES (12, 'placeholder');

INSERT INTO TESTUSER.ALLTYPE_TARGET (ID, CLOB_VAL)
VALUES (12, 'old clob');

-- Row 20: INSERT — source only, no row in target
INSERT INTO TESTUSER.ALLTYPE_SOURCE (ID, INT_VAL, STR_VAL, CLOB_VAL)
VALUES (20, 99, 'insert me', 'clob to insert');

-- Composite PK tables (REGION_ID NUMBER + DEPT_CODE VARCHAR2)
CREATE TABLE TESTUSER.COMPOSITE_SOURCE (
    REGION_ID   NUMBER(10),
    DEPT_CODE   VARCHAR2(20),
    VALUE       VARCHAR2(200),
    AMOUNT      NUMBER(15,2),
    CONSTRAINT pk_composite_src PRIMARY KEY (REGION_ID, DEPT_CODE)
);

CREATE TABLE TESTUSER.COMPOSITE_TARGET (
    REGION_ID   NUMBER(10),
    DEPT_CODE   VARCHAR2(20),
    VALUE       VARCHAR2(200),
    AMOUNT      NUMBER(15,2),
    CONSTRAINT pk_composite_tgt PRIMARY KEY (REGION_ID, DEPT_CODE)
);

-- Row 1: UPDATE
INSERT INTO TESTUSER.COMPOSITE_SOURCE (REGION_ID, DEPT_CODE, VALUE, AMOUNT)
VALUES (1, 'EAST', 'source value', 100.50);
INSERT INTO TESTUSER.COMPOSITE_TARGET (REGION_ID, DEPT_CODE, VALUE, AMOUNT)
VALUES (1, 'EAST', 'old value', 50.00);

-- Row 2: INSERT (source only)
INSERT INTO TESTUSER.COMPOSITE_SOURCE (REGION_ID, DEPT_CODE, VALUE, AMOUNT)
VALUES (2, 'WEST', 'new row', 200.00);

-- Timestamp PK tables (EVENT_ID + EVENT_TS TIMESTAMP(6))
CREATE TABLE TESTUSER.TSPK_SOURCE (
    EVENT_ID    NUMBER(10),
    EVENT_TS    TIMESTAMP(6),
    PAYLOAD     VARCHAR2(200),
    CONSTRAINT pk_tspk_src PRIMARY KEY (EVENT_ID, EVENT_TS)
);

CREATE TABLE TESTUSER.TSPK_TARGET (
    EVENT_ID    NUMBER(10),
    EVENT_TS    TIMESTAMP(6),
    PAYLOAD     VARCHAR2(200),
    CONSTRAINT pk_tspk_tgt PRIMARY KEY (EVENT_ID, EVENT_TS)
);

-- Row 1: UPDATE
INSERT INTO TESTUSER.TSPK_SOURCE (EVENT_ID, EVENT_TS, PAYLOAD)
VALUES (1, TIMESTAMP '2023-06-15 10:30:00', 'source payload');
INSERT INTO TESTUSER.TSPK_TARGET (EVENT_ID, EVENT_TS, PAYLOAD)
VALUES (1, TIMESTAMP '2023-06-15 10:30:00', 'old payload');

-- Row 2: INSERT (source only)
INSERT INTO TESTUSER.TSPK_SOURCE (EVENT_ID, EVENT_TS, PAYLOAD)
VALUES (2, TIMESTAMP '2023-06-16 12:00:00', 'new event payload');

-- Timezone-aware PK tables (EVENT_ID + EVENT_TS TIMESTAMP WITH TIME ZONE)
-- Row 1 is at UTC+0, row 2 is the same local time at UTC+8 — different UTC instants,
-- so they are distinct PK values and test that timezone offset survives the approve flow.
CREATE TABLE TESTUSER.TZPK_SOURCE (
    EVENT_ID    NUMBER(10),
    EVENT_TS    TIMESTAMP(6) WITH TIME ZONE,
    PAYLOAD     VARCHAR2(200),
    CONSTRAINT pk_tzpk_src PRIMARY KEY (EVENT_ID, EVENT_TS)
);

CREATE TABLE TESTUSER.TZPK_TARGET (
    EVENT_ID    NUMBER(10),
    EVENT_TS    TIMESTAMP(6) WITH TIME ZONE,
    PAYLOAD     VARCHAR2(200),
    CONSTRAINT pk_tzpk_tgt PRIMARY KEY (EVENT_ID, EVENT_TS)
);

-- Row 1: UTC+0 timestamp, UPDATE
INSERT INTO TESTUSER.TZPK_SOURCE (EVENT_ID, EVENT_TS, PAYLOAD)
VALUES (1, TIMESTAMP '2023-06-15 10:30:00 +00:00', 'utc source payload');
INSERT INTO TESTUSER.TZPK_TARGET (EVENT_ID, EVENT_TS, PAYLOAD)
VALUES (1, TIMESTAMP '2023-06-15 10:30:00 +00:00', 'utc old payload');

-- Row 2: UTC+8 timestamp (same local time, different UTC instant), UPDATE
INSERT INTO TESTUSER.TZPK_SOURCE (EVENT_ID, EVENT_TS, PAYLOAD)
VALUES (2, TIMESTAMP '2023-06-15 10:30:00 +08:00', 'utc8 source payload');
INSERT INTO TESTUSER.TZPK_TARGET (EVENT_ID, EVENT_TS, PAYLOAD)
VALUES (2, TIMESTAMP '2023-06-15 10:30:00 +08:00', 'utc8 old payload');

-- Row 3: UTC+0, INSERT (source only)
INSERT INTO TESTUSER.TZPK_SOURCE (EVENT_ID, EVENT_TS, PAYLOAD)
VALUES (3, TIMESTAMP '2023-06-16 08:00:00 +00:00', 'utc insert payload');

COMMIT;
