apiVersion: v1
kind: Secret
metadata:
  name: auditpatchx-secret
  namespace: auditpatchx
type: Opaque
stringData:
  db-url: "jdbc:oracle:thin:@//stock-trading-system-oracle-database.stocktrader.svc.cluster.local:1521/XEPDB1"
  db-user: "TRDMGMR"
  db-password: "REDACTED"
